[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.22"

[features]
seeds = false
skip-lint = false

[programs.devnet]
sablier_network_program = "H6CTDj7ewA6PT1jGt2WTnkhWb2RwwuoQkAsgzRuSsnaV"
sablier_thread_program = "sabGLGXfBiUCkwtprPMtatG6tCNxhcWWs1hjQAvDqEE"

[programs.localnet]
sablier_network_program = "H6CTDj7ewA6PT1jGt2WTnkhWb2RwwuoQkAsgzRuSsnaV"
sablier_thread_program = "sabGLGXfBiUCkwtprPMtatG6tCNxhcWWs1hjQAvDqEE"

[programs.mainnet]
sablier_network_program = "H6CTDj7ewA6PT1jGt2WTnkhWb2RwwuoQkAsgzRuSsnaV"
sablier_thread_program = "sabGLGXfBiUCkwtprPMtatG6tCNxhcWWs1hjQAvDqEE"

[programs.testnet]
sablier_network_program = "H6CTDj7ewA6PT1jGt2WTnkhWb2RwwuoQkAsgzRuSsnaV"
sablier_thread_program = "sabGLGXfBiUCkwtprPMtatG6tCNxhcWWs1hjQAvDqEE"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
