[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.2"

[features]
seeds = false
skip-lint = false

[programs.localnet]
sablier_network_program = "9ESdCQBeSnUspsKFmyoJTu1k4moMG6qbuK1BYVQsZ6Qc"
sablier_thread_program = "sabJknyNCneSXYhbNX1S1yU9fnT2tb7kUXA8SjHhDBX"
sablier_webhook_program = "GDZTj1Lxhp7cKoa69xzQRpYBSjN5bvp5KERpiojAoVAx"

[programs.mainnet]
sablier_network_program = "9ESdCQBeSnUspsKFmyoJTu1k4moMG6qbuK1BYVQsZ6Qc"
sablier_thread_program = "sabJknyNCneSXYhbNX1S1yU9fnT2tb7kUXA8SjHhDBX"
sablier_webhook_program = "GDZTj1Lxhp7cKoa69xzQRpYBSjN5bvp5KERpiojAoVAx"

[programs.testnet]
sablier_network_program = "9ESdCQBeSnUspsKFmyoJTu1k4moMG6qbuK1BYVQsZ6Qc"
sablier_thread_program = "sabJknyNCneSXYhbNX1S1yU9fnT2tb7kUXA8SjHhDBX"
sablier_webhook_program = "GDZTj1Lxhp7cKoa69xzQRpYBSjN5bvp5KERpiojAoVAx"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
