[toolchain]
channel = "1.73.0"
components = ["rustfmt", "rust-analyzer", "clippy"]
profile = "minimal"
targets = [
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
]
